version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:

      - redis

    environment:
      DATABASE_URL: postgresql://neondb_owner:bU72tdScmnFR@ep-falling-wind-a6vk1q59-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require
      NODE_ENV: development
      PORT: 8080
      REDIS: 6379
      API_KEY: a2308fead3fdd1a047f4677d83462aa3
      API_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhMjMwOGZlYWQzZmRkMWEwNDdmNDY3N2Q4MzQ2MmFhMyIsIm5iZiI6MTcxOTQ0MzYxMi4zODI1MjUsInN1YiI6IjY0ZjM0NDE4ZTBjYTdmMDEyZWIzOGQyYSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-kPjbDprvsAvhLLAeUgnj7ru938mHQTvBCAnuBopFOA
    ports:
      - '8080:8080'
    networks:
      - mynetwork


      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      - mynetwork


networks:
  mynetwork:
